name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"   # Каждый день в полночь
  workflow_dispatch:       # Ручной запуск

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout output branch
        uses: actions/checkout@v4
        with:
          ref: output
          
      - name: Generate snake for both themes
        uses: Platane/snk@v3
        with:
          github_user_name: maerdlina
          outputs: |
            github-contribution-grid-snake.svg          # для светлой темы
            github-contribution-grid-snake-dark.svg?palette=github-dark  # для тёмной темы
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Commit and push snake files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "🔄 Update snake animations for both themes - $(date +'%Y-%m-%d')"
          git push origin output
